name: Publish artifacts

on:
  push:
    tags:
      - '*'

env:
  ROCK_NAME: "migrations-ee"

jobs:
  version-check:
    # We need this job to run only on push with tag.
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: [self-hosted, Linux, x86_64, regular]
    container:
      image: ubuntu:22.04
    steps:
      - name: Clone the module
        uses: actions/checkout@v3

      - name: Prepare env
        uses: ./.github/actions/prepare-env
        with:
          tarantool-version: '2.11'

      - name: Check module version
        uses: tarantool/actions/check-module-version@master
        with:
          module-name: 'migrator-ee'

  push-tagged-rock:
    runs-on: [self-hosted, Linux, x86_64, regular]
    container:
      image: ubuntu:22.04
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    needs: version-check
    steps:
      - name: Clone the module
        uses: actions/checkout@v3

      - name: Prepare env
        uses: ./.github/actions/prepare-env
        with:
          tarantool-version: '2.11'

      - name: Install aws
        run: |
          apt-get -y update
          apt-get --allow-releaseinfo-change update
          apt-get -y install awscli
        env:
          DEBIAN_FRONTEND: noninteractive
        shell: bash

      # https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
      - name: Set env
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create release rockspec
        run: |
          sed \
            -e "s/branch = '.\+'/tag = '${GIT_TAG}'/g" \
            -e "s/version = '.\+'/version = '${GIT_TAG}-1'/g" \
            ${{ env.ROCK_NAME }}-scm-1.rockspec > ${{ env.ROCK_NAME }}-${GIT_TAG}-1.rockspec

      - run: tt rocks make ${{ env.ROCK_NAME }}-${GIT_TAG}-1.rockspec

      - run: tt rocks pack ${{ env.ROCK_NAME }} ${GIT_TAG}

      - name: Push release rock
        run: aws --endpoint-url "https://hb.vkcs.cloud" s3 cp ./${{ env.ROCK_NAME }}-*.all.rock "s3://packages/rocks/"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
