name: Publish

on:
  push:
    branches: [master]
    tags: ['*']

jobs:
  version-check:
    # We need this job to run only on push with tag.
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}

    runs-on: [self-hosted, Linux, x86_64, regular]
    container:
      image: ubuntu:22.04

    steps:
      - name: Check module version
        uses: tarantool/actions/check-module-version@master
        with:
          module-name: 'migrator'

  publish-tag:
    if: startsWith(github.ref, 'refs/tags/')
    needs: version-check

    runs-on: [self-hosted, Linux, x86_64, regular]
    container:
      image: ubuntu:22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install basic tools
        run: |
          apt-get -y update
          apt-get --allow-releaseinfo-change update
          apt-get -y install sudo git curl gcc make cmake unzip \
          zip gawk cpio pkg-config build-essential ninja-build \
          liblz4-dev autoconf automake libtool lsb-release rsync libunwind-dev \
        shell: bash

      # tzdata package, which is tarantool dependency, asks a user for time zone configuration. The
      # step below disables user interaction for this package.
      - name: Set tzdata
        run: |
          ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime
          echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
          echo "TZ=Europe/Moscow" >> $GITHUB_ENV
        shell: bash

      # Workaround for setup tarantool action: disable dpkg filters, so all files will be installed.
      - name: Disable default dpkg excludes
        run: echo "" > /etc/dpkg/dpkg.cfg.d/excludes
        shell: bash

      - name: Install tarantool
        uses: tarantool/setup-tarantool@v3
        with:
          tarantool-version: '2.10'

      - run: echo $PWD/.rocks/bin >> $GITHUB_PATH

      # Make a release
      - run: echo TAG=${GITHUB_REF##*/} >> $GITHUB_ENV
      - run: tarantoolctl rocks new_version --tag ${{ env.TAG }}
      - run: tarantoolctl rocks install migrations-${{ env.TAG }}-1.rockspec
      - run: tarantoolctl rocks pack migrations ${{ env.TAG }}
