name: Publish artifacts

on:
  push:
    tags:
      - '*'

env:
  ROCK_NAME: "migrations-ee"

jobs:
  version-check:
    # We need this job to run only on push with tag.
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: [self-hosted, Linux, x86_64, regular]
    container:
      image: ubuntu:22.04
    steps:
      - name: Clone the module
        uses: actions/checkout@v3

      - name: Prepare env
        uses: ./.github/actions/prepare-env
        with:
          tarantool-version: '2.11'

      - name: Install requirements
        run: make .rocks
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # tarantool/actions/check-module-version@master tries to install vshard-ee scm from net
      # and fails (even though there is already vshard-ee 0.1.27)
      - name: Check package version
        run: |
          REPO_TAG=${{ github.ref_name }}
          MODULE_VERSION=$(tarantool -e "print(require('migrator-ee')._VERSION)")
          echo "Module name is ${{ env.ROCK_NAME }}"
          echo "Detected version from code is $MODULE_VERSION"
          echo "Detected repo tag is $REPO_TAG"
          if [ "$MODULE_VERSION" != "$REPO_TAG" ]; then
            echo "::error::Version from code and the last repository tag are not equal"
            echo "::notice::You may have forgotten to update the value in the version.lua file"
            exit 1
          fi

  push-tagged-rock:
    runs-on: [self-hosted, Linux, x86_64, regular]
    container:
      image: ubuntu:22.04
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    needs: version-check
    steps:
      - name: Clone the module
        uses: actions/checkout@v3

      - name: Prepare env
        uses: ./.github/actions/prepare-env
        with:
          tarantool-version: '2.11'

      - name: Install requirements
        run: make .rocks
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
      - name: Set env
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create release rockspec
        run: |
          sed \
            -e "s/branch = '.\+'/tag = '${GIT_TAG}'/g" \
            -e "s/version = '.\+'/version = '${GIT_TAG}-1'/g" \
            ${{ env.ROCK_NAME }}-scm-1.rockspec > ${{ env.ROCK_NAME }}-${GIT_TAG}-1.rockspec

      - run: tt rocks make ${{ env.ROCK_NAME }}-${GIT_TAG}-1.rockspec

      - run: tt rocks pack ${{ env.ROCK_NAME }} ${GIT_TAG}

      - name: Push release rock
        run: aws --endpoint-url "https://hb.vkcs.cloud" s3 cp ./${{ env.ROCK_NAME }}-*.all.rock "s3://packages/rocks/"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
