name: Publish

on:
  push:
    branches: [master]
    tags: ['*']

jobs:
  publish-scm-1:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: tarantool/rocks.tarantool.org/github-action@master
        with:
          auth: ${{ secrets.ROCKS_AUTH }}
          files: migrations-scm-1.rockspec

  publish-tag:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: '2.5'
      - run: echo $PWD/.rocks/bin >> $GITHUB_PATH

      # Make a release
      - run: echo TAG=${GITHUB_REF##*/} >> $GITHUB_ENV
      - run: tarantoolctl rocks new_version --tag ${{ env.TAG }}
      - run: tarantoolctl rocks install migrations-${{ env.TAG }}-1.rockspec
      - run: tarantoolctl rocks pack migrations ${{ env.TAG }}

      - uses: tarantool/rocks.tarantool.org/github-action@master
        with:
          auth: ${{ secrets.ROCKS_AUTH }}
          files: |
            migrations-${{ env.TAG }}-1.rockspec
            migrations-${{ env.TAG }}-1.all.rock
