name: Run tests

on: [push]

jobs:
  all:
    runs-on: [self-hosted, Linux, x86_64, regular]
    container:
      image: ubuntu:22.04

    steps:
      - name: Clone the module
        uses: actions/checkout@v3

      - name: Prepare env
        uses: ./.github/actions/prepare-env
        with:
          tarantool-version: '2.11'

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install rocks
        shell: bash
        run: make .rocks
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run tests
        run: make test

